{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.lgatodu47",
    "module": "catconfig-mc",
    "version": "1.20.4-0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "catconfig-mc-1.20.4-0.2.1.jar",
          "url": "catconfig-mc-1.20.4-0.2.1.jar",
          "size": 151436,
          "sha512": "f104c552b06ee4769caf88a34b170d840270a58f040e509131e806b93e32cfab322822310ad650a3648617972d046d52114d44133902b66e6e81f4798344e871",
          "sha256": "869f7a6dc7d1ce14503de8fd8076d16ee21fe8449c424927376249c65e91d50b",
          "sha1": "b8a4927f701c522bfea3f38a9eb827eacf20b0f2",
          "md5": "d1082cd65e6d90c32aaa8900b79cdb76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.lgatodu47",
          "module": "catconfig",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "catconfig-mc-1.20.4-0.2.1.jar",
          "url": "catconfig-mc-1.20.4-0.2.1.jar",
          "size": 151436,
          "sha512": "f104c552b06ee4769caf88a34b170d840270a58f040e509131e806b93e32cfab322822310ad650a3648617972d046d52114d44133902b66e6e81f4798344e871",
          "sha256": "869f7a6dc7d1ce14503de8fd8076d16ee21fe8449c424927376249c65e91d50b",
          "sha1": "b8a4927f701c522bfea3f38a9eb827eacf20b0f2",
          "md5": "d1082cd65e6d90c32aaa8900b79cdb76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "catconfig-mc-1.20.4-0.2.1-sources.jar",
          "url": "catconfig-mc-1.20.4-0.2.1-sources.jar",
          "size": 78162,
          "sha512": "36a0be0653630c0a112998e10be179bde23a4c8379fe8b0caf63255ab5a52d0808ad977e87dcd8cac68ea55837b3d7df627f98d30780464baa0c0d8e35010d9f",
          "sha256": "a1f268e5b2ecaed5fdc2f4f8b8a277a9df618545cdddea40c5ef966e28b29031",
          "sha1": "960f6fbd25bb46a530af0fae89f7cbf53192a850",
          "md5": "bee0eb9f81aea563cbd5f6d2e557ceb0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "catconfig-mc-1.20.4-0.2.1-javadoc.jar",
          "url": "catconfig-mc-1.20.4-0.2.1-javadoc.jar",
          "size": 179716,
          "sha512": "5fd8163eee611e303c0c28b883fe348ade7193dee9f171481644ff352faf6fec46f78aa75bfeec9de434ca60ddea3e4814c273b38f77d6b54ea21c1ba4031490",
          "sha256": "5c87c034521ee5c72077850345257ee8070a1f1314460ce476b1d34db769fe4a",
          "sha1": "75b76f65d9823a3c251cf864075b0f366baead36",
          "md5": "839f23d0817da29770eceb6a858eac3f"
        }
      ]
    }
  ]
}
